apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  restartPolicy: Always
  imagePullSecrets:
    - name: srinu
  containers:
    - name: httpd-container
      image: srinu9666/httpd:v1
      imagePullPolicy: Always
      ports:
        - containerPort: 8800
