apiVersion: v1
kind: Pod
metadata:
  name: my-app-1
  labels:
    app: my-app-1
spec:
  restartPolicy: Always
  imagePullSecrets:
    - name: srinu
  containers:
    - name: httpd-container
      image: srinu9666/sree:v1
      imagePullPolicy: Always
      ports:
        - containerPort: 8800
