apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  restartPolicy: Always
  imagePullSecrets:
    - name: srinu12
  containers:
    - name: httpd-container
      image: 851051434871.dkr.ecr.us-east-1.amazonaws.com/srinu12:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 80
